[package]
name = "uefi-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
uefi = { version = "0.33.0", features = [
    "logger",
    "global_allocator",
    "alloc",
] }
thiserror-no-std = "2.0.2"
goblin = { version = "0.9.2", default-features = false, features = [
    "elf64",
    "elf32",
    "endian_fd",
] }

# todo: change these to the gihtub repos
framebuffer = { path = "../graphics-core/framebuffer" }
fonts = { path = "../graphics-core/fonts" }
sync = { path = "../sync" }
bootinfo = { path = "../bootinfo" }
mem = { path = "../mem" }
hal = { path = "../hal" }
