[package]
name = "uefi-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
uefi = { version = "0.33.0", features = [
    "logger",
    "global_allocator",
    "alloc",
] }
qemu_print = "0.1.0"
