[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootinfo = { path = "../bootinfo" }
mem = { path = "../mem" }
framebuffer = { path = "../framebuffer" }
hal = { path = "../hal" }
sync = { path = "../sync" }

bitflags = "2.6.0"
paste = "1.0.15"
